version: "3.9"
services:
  pgvector:
    build:
      context: .
      dockerfile: docker/pgvector.dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  llama-app:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/service-account-key.json
      - ENV=docker
      - PROJECT_ID=production-397416
      - ENDPOINT_ID=8535660499029721088
      - REGION=us-central1
    build:
      context: .
      dockerfile: docker/app.dockerfile
    container_name: llama-app
    command: "python -m uvicorn app:app --app-dir /app/llama_app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - "5000:5000"
    depends_on:
      - pgvector
    volumes:
      - ".:/app"
      - /home/rita/Desktop/local/llama-lab/secrets/production-397416-25b4cdf035c6.json:/tmp/keys/service-account-key.json
volumes:
  pgdata: