version: '3.1'

services:
  auth_example:
    build:
      context: .
      dockerfile: docker/auth-example.dockerfile
    volumes:
      - "${HOME}/.config/gcloud:/root/.config/gcloud"
    environment:
      - PROJECT_ID=${PROJECT_ID}
